# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: false
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: ACSONE SA/NV
org_slug: acsone
rebel_module_groups: []
repo_description: 'Alfodoo is a set of addons to seamlessly integrate an external
    Document Management System with Odoo.


    '
repo_name: Alfodoo
repo_slug: alfodoo
repo_website: https://alfodoo.org
travis_apt_packages: []
travis_apt_sources: []

