# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: false
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: ACSONE SA/NV
org_slug: acsone
rebel_module_groups: []
repo_description: null
repo_name: Alfodoo
repo_slug: alfodoo
repo_website: https://alfodoo.org
travis_apt_packages: []
travis_apt_sources: []

