all: \
  ../cmis_alf/static/description/main_icon.png \
  ../cmis_alf/static/description/icon.png \
  ../cmis_field/static/description/main_icon.png \
  ../cmis_field/static/description/icon.png \
  ../cmis_web/static/description/main_icon.png \
  ../cmis_web/static/description/icon.png \
  ../cmis_web_alf/static/description/main_icon.png \
  ../cmis_web_alf/static/description/icon.png \
  ../cmis_web_proxy/static/description/main_icon.png \
  ../cmis_web_proxy/static/description/icon.png \
  ../cmis_web_proxy_alf/static/description/main_icon.png \
  ../cmis_web_proxy_alf/static/description/icon.png \
  ../cmis_web_alf/doc/index.rst


../cmis_web_alf/doc/index.rst: ../doc/guides/short_guide.rst
	cp $< $@

../cmis_alf/static/description/main_icon.png: _static/logo.png
	cp $< $@

../cmis_alf/static/description/icon.png: _static/icon.png
	cp $< $@

../cmis_field/static/description/main_icon.png: _static/logo.png
	cp $< $@

../cmis_field/static/description/icon.png: _static/icon.png
	cp $< $@

../cmis_web/static/description/main_icon.png: _static/logo.png
	cp $< $@

../cmis_web/static/description/icon.png: _static/icon.png
	cp $< $@

../cmis_web_alf/static/description/main_icon.png: _static/logo.png
	cp $< $@

../cmis_web_alf/static/description/icon.png: _static/icon.png
	cp $< $@

../cmis_web_proxy/static/description/main_icon.png: _static/logo.png
	cp $< $@

../cmis_web_proxy/static/description/icon.png: _static/icon.png
	cp $< $@

../cmis_web_proxy_alf/static/description/main_icon.png: _static/logo.png
	cp $< $@

../cmis_web_proxy_alf/static/description/icon.png: _static/icon.png
	cp $< $@
